# Generated by Django 3.1.3 on 2020-11-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201127_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='slugname',
            field=models.SlugField(default='undefined', max_length=30, verbose_name='slugname'),
            preserve_default=False,
        ),
    ]
