# Generated by Django 3.1.3 on 2020-11-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_anime_slugname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='slugname',
        ),
        migrations.AddField(
            model_name='anime',
            name='slugTitle',
            field=models.SlugField(default='undef', max_length=30, verbose_name='slugTitle'),
            preserve_default=False,
        ),
    ]
