# Generated by Django 3.1.3 on 2020-12-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='slugTitle',
            field=models.SlugField(default='slug', max_length=30, verbose_name='slugTitle'),
            preserve_default=False,
        ),
    ]
